# permissions for end users to edit secretstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretstore-editor-role
rules:
- apiGroups:
  - external-secrets.io
  resources:
  - secretstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - external-secrets.io
  resources:
  - secretstores/status
  verbs:
  - get
